services:
  backend:
    build: ./javafiles
    container_name: javafiles
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/javafiles_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 326598
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
      - app-network
    restart: always

  frontend:
    build: ./file-system-frontend
    container_name: file-system-frontend
    ports:
      - "4200:4200"  # Mapeia a porta 4200 do contêiner para a 4200 do host
    networks:
      - app-network
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true  # Corrige possíveis problemas de hot-reload no Docker

  mysql:
    image: mysql:8.0
    container_name: javafiles-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 326598
      MYSQL_DATABASE: javafiles_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
