services:
  javafiles:
    build: .
    container_name: javafiles
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/javafiles_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 326598

  mysql:
    image: mysql:8.0
    container_name: javafiles-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 326598
      MYSQL_DATABASE: javafiles_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: